// prisma/seeds/coa-ifrs.seed.ts
// IFRS Chart of Accounts — IAS-compliant template for Pakistan market
// Based on IAS 1 (Presentation), IAS 7 (Cash Flow), IAS 16 (PPE), IAS 38 (Intangibles)

import { AccountType } from '@prisma/client';
import type { SeedAccount } from './coa-gaap.seed';

export const IFRS_ACCOUNTS: SeedAccount[] = [
  // ── NON-CURRENT ASSETS (1000) ────────────────────────────────────────────
  { accountCode: '1000', name: 'Non-Current Assets', type: AccountType.ASSET, subType: 'Summary' },

  {
    accountCode: '1100',
    name: 'Property, Plant & Equipment (Net)',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1000',
  },
  {
    accountCode: '1110',
    name: 'Land & Buildings — Cost',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1100',
  },
  {
    accountCode: '1111',
    name: 'Land — Cost',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1110',
  },
  {
    accountCode: '1112',
    name: 'Buildings — Cost',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1110',
  },
  {
    accountCode: '1113',
    name: 'Accumulated Depreciation — Buildings',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1110',
    description: 'Contra asset',
  },
  {
    accountCode: '1120',
    name: 'Plant & Machinery — Cost',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1100',
  },
  {
    accountCode: '1121',
    name: 'Accumulated Depreciation — Plant',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1120',
    description: 'Contra asset',
  },
  {
    accountCode: '1130',
    name: 'Vehicles — Cost',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1100',
  },
  {
    accountCode: '1131',
    name: 'Accumulated Depreciation — Vehicles',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1130',
    description: 'Contra asset',
  },
  {
    accountCode: '1140',
    name: 'Right-of-Use Assets (IFRS 16)',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1100',
  },
  {
    accountCode: '1141',
    name: 'Accumulated Amortisation — ROU',
    type: AccountType.ASSET,
    subType: 'PPE',
    parentCode: '1140',
    description: 'Contra asset',
  },

  {
    accountCode: '1200',
    name: 'Intangible Assets',
    type: AccountType.ASSET,
    subType: 'Intangible',
    parentCode: '1000',
  },
  {
    accountCode: '1210',
    name: 'Goodwill',
    type: AccountType.ASSET,
    subType: 'Intangible',
    parentCode: '1200',
  },
  {
    accountCode: '1220',
    name: 'Other Intangibles — Cost',
    type: AccountType.ASSET,
    subType: 'Intangible',
    parentCode: '1200',
  },
  {
    accountCode: '1221',
    name: 'Customer Relationships',
    type: AccountType.ASSET,
    subType: 'Intangible',
    parentCode: '1220',
  },
  {
    accountCode: '1222',
    name: 'Technology & Software',
    type: AccountType.ASSET,
    subType: 'Intangible',
    parentCode: '1220',
  },
  {
    accountCode: '1223',
    name: 'Accumulated Amortisation — Intangibles',
    type: AccountType.ASSET,
    subType: 'Intangible',
    parentCode: '1220',
    description: 'Contra asset',
  },

  {
    accountCode: '1300',
    name: 'Financial Assets — Non-Current',
    type: AccountType.ASSET,
    subType: 'Financial Asset',
    parentCode: '1000',
  },
  {
    accountCode: '1310',
    name: 'Investments in Associates',
    type: AccountType.ASSET,
    subType: 'Financial Asset',
    parentCode: '1300',
  },
  {
    accountCode: '1320',
    name: 'Equity Investments at FVOCI',
    type: AccountType.ASSET,
    subType: 'Financial Asset',
    parentCode: '1300',
  },
  {
    accountCode: '1330',
    name: 'Long-Term Deposits',
    type: AccountType.ASSET,
    subType: 'Financial Asset',
    parentCode: '1300',
  },

  {
    accountCode: '1400',
    name: 'Deferred Tax Asset',
    type: AccountType.ASSET,
    subType: 'Deferred Tax',
    parentCode: '1000',
  },

  // ── CURRENT ASSETS (2000) ────────────────────────────────────────────────
  { accountCode: '2000', name: 'Current Assets', type: AccountType.ASSET, subType: 'Summary' },
  {
    accountCode: '2100',
    name: 'Inventories',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2000',
  },
  {
    accountCode: '2110',
    name: 'Raw Materials',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2100',
  },
  {
    accountCode: '2120',
    name: 'Work in Progress',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2100',
  },
  {
    accountCode: '2130',
    name: 'Finished Goods',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2100',
  },
  {
    accountCode: '2200',
    name: 'Trade & Other Receivables',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2000',
  },
  {
    accountCode: '2210',
    name: 'Trade Receivables',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2200',
  },
  {
    accountCode: '2211',
    name: 'Loss Allowance (ECL)',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2210',
    description: 'Expected Credit Loss — IFRS 9 contra asset',
  },
  {
    accountCode: '2220',
    name: 'Other Receivables',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2200',
  },
  {
    accountCode: '2230',
    name: 'Prepayments',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2200',
  },
  {
    accountCode: '2300',
    name: 'Contract Assets (IFRS 15)',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2000',
  },
  {
    accountCode: '2400',
    name: 'Financial Assets — Current',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2000',
  },
  {
    accountCode: '2410',
    name: 'Short-Term Investments',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2400',
  },
  {
    accountCode: '2500',
    name: 'Cash & Cash Equivalents',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2000',
  },
  {
    accountCode: '2510',
    name: 'Cash in Hand',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2500',
  },
  {
    accountCode: '2520',
    name: 'Cash at Bank — HBL',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2500',
  },
  {
    accountCode: '2521',
    name: 'Cash at Bank — MCB',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2500',
  },
  {
    accountCode: '2530',
    name: 'Foreign Currency Accounts',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '2500',
  },

  // ── EQUITY (3000) ────────────────────────────────────────────────────────
  { accountCode: '3000', name: 'Equity', type: AccountType.EQUITY, subType: 'Summary' },
  {
    accountCode: '3100',
    name: 'Share Capital',
    type: AccountType.EQUITY,
    subType: 'Share Capital',
    parentCode: '3000',
  },
  {
    accountCode: '3110',
    name: 'Authorised Capital',
    type: AccountType.EQUITY,
    subType: 'Share Capital',
    parentCode: '3100',
  },
  {
    accountCode: '3120',
    name: 'Issued & Paid-up Capital',
    type: AccountType.EQUITY,
    subType: 'Share Capital',
    parentCode: '3100',
  },
  {
    accountCode: '3200',
    name: 'Other Components of Equity',
    type: AccountType.EQUITY,
    subType: 'Reserves',
    parentCode: '3000',
  },
  {
    accountCode: '3210',
    name: 'Share Premium',
    type: AccountType.EQUITY,
    subType: 'Reserves',
    parentCode: '3200',
  },
  {
    accountCode: '3220',
    name: 'Revaluation Surplus',
    type: AccountType.EQUITY,
    subType: 'Reserves',
    parentCode: '3200',
  },
  {
    accountCode: '3230',
    name: 'OCI — FVOCI Reserve',
    type: AccountType.EQUITY,
    subType: 'Reserves',
    parentCode: '3200',
  },
  {
    accountCode: '3240',
    name: 'Translation Reserve',
    type: AccountType.EQUITY,
    subType: 'Reserves',
    parentCode: '3200',
  },
  {
    accountCode: '3300',
    name: 'Retained Earnings',
    type: AccountType.EQUITY,
    subType: 'Retained Earnings',
    parentCode: '3000',
  },
  {
    accountCode: '3310',
    name: 'Retained Earnings — B/F',
    type: AccountType.EQUITY,
    subType: 'Retained Earnings',
    parentCode: '3300',
  },
  {
    accountCode: '3320',
    name: 'Profit for the Period',
    type: AccountType.EQUITY,
    subType: 'Retained Earnings',
    parentCode: '3300',
  },
  {
    accountCode: '3400',
    name: 'Dividends',
    type: AccountType.EQUITY,
    subType: 'Dividends',
    parentCode: '3000',
  },

  // ── NON-CURRENT LIABILITIES (4000) ──────────────────────────────────────
  {
    accountCode: '4000',
    name: 'Non-Current Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Summary',
  },
  {
    accountCode: '4100',
    name: 'Borrowings — Non-Current',
    type: AccountType.LIABILITY,
    subType: 'Borrowings',
    parentCode: '4000',
  },
  {
    accountCode: '4110',
    name: 'Long-Term Bank Loans',
    type: AccountType.LIABILITY,
    subType: 'Borrowings',
    parentCode: '4100',
  },
  {
    accountCode: '4120',
    name: 'Bonds Payable',
    type: AccountType.LIABILITY,
    subType: 'Borrowings',
    parentCode: '4100',
  },
  {
    accountCode: '4200',
    name: 'Lease Liabilities — Non-Current (IFRS 16)',
    type: AccountType.LIABILITY,
    subType: 'Lease',
    parentCode: '4000',
  },
  {
    accountCode: '4300',
    name: 'Deferred Tax Liability',
    type: AccountType.LIABILITY,
    subType: 'Deferred Tax',
    parentCode: '4000',
  },
  {
    accountCode: '4400',
    name: 'Employee Benefit Obligations (IAS 19)',
    type: AccountType.LIABILITY,
    subType: 'Employee Benefits',
    parentCode: '4000',
  },
  {
    accountCode: '4410',
    name: 'Defined Benefit Obligation',
    type: AccountType.LIABILITY,
    subType: 'Employee Benefits',
    parentCode: '4400',
  },
  {
    accountCode: '4420',
    name: 'Gratuity Payable',
    type: AccountType.LIABILITY,
    subType: 'Employee Benefits',
    parentCode: '4400',
  },

  // ── CURRENT LIABILITIES (5000) ───────────────────────────────────────────
  {
    accountCode: '5000',
    name: 'Current Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Summary',
  },
  {
    accountCode: '5100',
    name: 'Trade & Other Payables',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5000',
  },
  {
    accountCode: '5110',
    name: 'Trade Payables',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5100',
  },
  {
    accountCode: '5120',
    name: 'Accrued Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5100',
  },
  {
    accountCode: '5121',
    name: 'Accrued Salaries',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5120',
  },
  {
    accountCode: '5122',
    name: 'Accrued EOBI/SESSI',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5120',
  },
  {
    accountCode: '5130',
    name: 'Contract Liabilities (IFRS 15)',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5100',
  },
  {
    accountCode: '5200',
    name: 'Taxes Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5000',
  },
  {
    accountCode: '5210',
    name: 'Income Tax Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5200',
  },
  {
    accountCode: '5220',
    name: 'Sales Tax / GST Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5200',
  },
  {
    accountCode: '5230',
    name: 'WHT Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5200',
  },
  {
    accountCode: '5300',
    name: 'Borrowings — Current',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5000',
  },
  {
    accountCode: '5400',
    name: 'Lease Liabilities — Current (IFRS 16)',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '5000',
  },

  // ── REVENUE (6000) ───────────────────────────────────────────────────────
  { accountCode: '6000', name: 'Revenue (IFRS 15)', type: AccountType.REVENUE, subType: 'Summary' },
  {
    accountCode: '6100',
    name: 'Revenue from Contracts with Customers',
    type: AccountType.REVENUE,
    subType: 'Revenue',
    parentCode: '6000',
  },
  {
    accountCode: '6110',
    name: 'Goods Transferred at Point in Time',
    type: AccountType.REVENUE,
    subType: 'Revenue',
    parentCode: '6100',
  },
  {
    accountCode: '6120',
    name: 'Services over Time',
    type: AccountType.REVENUE,
    subType: 'Revenue',
    parentCode: '6100',
  },
  {
    accountCode: '6130',
    name: 'SaaS Subscription Revenue',
    type: AccountType.REVENUE,
    subType: 'Revenue',
    parentCode: '6100',
  },
  {
    accountCode: '6140',
    name: 'Variable Consideration',
    type: AccountType.REVENUE,
    subType: 'Revenue',
    parentCode: '6100',
  },
  {
    accountCode: '6200',
    name: 'Other Income',
    type: AccountType.REVENUE,
    subType: 'Other Income',
    parentCode: '6000',
  },
  {
    accountCode: '6210',
    name: 'Finance Income',
    type: AccountType.REVENUE,
    subType: 'Other Income',
    parentCode: '6200',
  },
  {
    accountCode: '6220',
    name: 'Dividend Income',
    type: AccountType.REVENUE,
    subType: 'Other Income',
    parentCode: '6200',
  },
  {
    accountCode: '6230',
    name: 'Gain on Disposal of Assets',
    type: AccountType.REVENUE,
    subType: 'Other Income',
    parentCode: '6200',
  },
  {
    accountCode: '6240',
    name: 'FX Gains',
    type: AccountType.REVENUE,
    subType: 'Other Income',
    parentCode: '6200',
  },

  // ── EXPENSES (7000) ──────────────────────────────────────────────────────
  {
    accountCode: '7000',
    name: 'Cost of Sales',
    type: AccountType.EXPENSE,
    subType: 'Cost of Sales',
  },
  {
    accountCode: '7100',
    name: 'Direct Materials',
    type: AccountType.EXPENSE,
    subType: 'Cost of Sales',
    parentCode: '7000',
  },
  {
    accountCode: '7200',
    name: 'Direct Labour',
    type: AccountType.EXPENSE,
    subType: 'Cost of Sales',
    parentCode: '7000',
  },
  {
    accountCode: '7300',
    name: 'Manufacturing Overhead',
    type: AccountType.EXPENSE,
    subType: 'Cost of Sales',
    parentCode: '7000',
  },

  {
    accountCode: '8000',
    name: 'Distribution Costs',
    type: AccountType.EXPENSE,
    subType: 'Distribution',
  },
  {
    accountCode: '8100',
    name: 'Freight & Logistics',
    type: AccountType.EXPENSE,
    subType: 'Distribution',
    parentCode: '8000',
  },
  {
    accountCode: '8200',
    name: 'Sales & Marketing',
    type: AccountType.EXPENSE,
    subType: 'Distribution',
    parentCode: '8000',
  },
  {
    accountCode: '8210',
    name: 'Advertising',
    type: AccountType.EXPENSE,
    subType: 'Distribution',
    parentCode: '8200',
  },
  {
    accountCode: '8220',
    name: 'Sales Commissions',
    type: AccountType.EXPENSE,
    subType: 'Distribution',
    parentCode: '8200',
  },

  {
    accountCode: '9000',
    name: 'Administrative Expenses',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
  },
  {
    accountCode: '9100',
    name: 'Staff Costs',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9000',
  },
  {
    accountCode: '9110',
    name: 'Salaries & Wages',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9100',
  },
  {
    accountCode: '9120',
    name: 'Employee Benefits (IAS 19)',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9100',
  },
  {
    accountCode: '9121',
    name: 'Provident Fund',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9120',
  },
  {
    accountCode: '9122',
    name: 'EOBI Employer Contribution',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9120',
  },
  {
    accountCode: '9130',
    name: 'Share-Based Payments (IFRS 2)',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9100',
  },
  {
    accountCode: '9200',
    name: 'Depreciation & Amortisation',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9000',
  },
  {
    accountCode: '9210',
    name: 'Depreciation — PPE',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9200',
  },
  {
    accountCode: '9220',
    name: 'Amortisation — Intangibles',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9200',
  },
  {
    accountCode: '9230',
    name: 'Amortisation — ROU Assets',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9200',
  },
  {
    accountCode: '9300',
    name: 'Office & General',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9000',
  },
  {
    accountCode: '9310',
    name: 'Rent Expense',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9300',
  },
  {
    accountCode: '9320',
    name: 'Professional Services',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9300',
  },
  {
    accountCode: '9330',
    name: 'IT & Technology',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9300',
  },
  {
    accountCode: '9340',
    name: 'Insurance',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9300',
  },
  {
    accountCode: '9350',
    name: 'Travel & Entertainment',
    type: AccountType.EXPENSE,
    subType: 'Administrative',
    parentCode: '9300',
  },
  {
    accountCode: '9400',
    name: 'Impairment Losses (IAS 36)',
    type: AccountType.EXPENSE,
    subType: 'Impairment',
    parentCode: '9000',
  },
  {
    accountCode: '9410',
    name: 'Impairment — Goodwill',
    type: AccountType.EXPENSE,
    subType: 'Impairment',
    parentCode: '9400',
  },
  {
    accountCode: '9420',
    name: 'Impairment — Receivables (ECL)',
    type: AccountType.EXPENSE,
    subType: 'Impairment',
    parentCode: '9400',
  },

  {
    accountCode: '9500',
    name: 'Finance Costs',
    type: AccountType.EXPENSE,
    subType: 'Finance Costs',
  },
  {
    accountCode: '9510',
    name: 'Interest Expense',
    type: AccountType.EXPENSE,
    subType: 'Finance Costs',
    parentCode: '9500',
  },
  {
    accountCode: '9511',
    name: 'Interest on Bank Loans',
    type: AccountType.EXPENSE,
    subType: 'Finance Costs',
    parentCode: '9510',
  },
  {
    accountCode: '9512',
    name: 'Interest on Lease Liabilities (IFRS 16)',
    type: AccountType.EXPENSE,
    subType: 'Finance Costs',
    parentCode: '9510',
  },
  {
    accountCode: '9520',
    name: 'Foreign Exchange Loss',
    type: AccountType.EXPENSE,
    subType: 'Finance Costs',
    parentCode: '9500',
  },

  { accountCode: '9600', name: 'Income Tax Expense', type: AccountType.EXPENSE, subType: 'Tax' },
  {
    accountCode: '9610',
    name: 'Current Tax',
    type: AccountType.EXPENSE,
    subType: 'Tax',
    parentCode: '9600',
  },
  {
    accountCode: '9620',
    name: 'Deferred Tax',
    type: AccountType.EXPENSE,
    subType: 'Tax',
    parentCode: '9600',
  },
];
