// prisma/seeds/coa-gaap.seed.ts
// GAAP USA Chart of Accounts — Standard template
// Account codes follow the standard 1000–9999 numbering convention.
// Hierarchy: top-level accounts own sub-accounts via parentCode field.

import { AccountType } from '@prisma/client';

export interface SeedAccount {
  accountCode: string;
  name: string;
  type: AccountType;
  subType: string;
  parentCode?: string; // resolved to parentId during import
  description?: string;
}

export const GAAP_USA_ACCOUNTS: SeedAccount[] = [
  // ── ASSETS (1000–1999) ───────────────────────────────────────────────────
  { accountCode: '1000', name: 'Assets', type: AccountType.ASSET, subType: 'Summary' },

  // Current Assets
  {
    accountCode: '1100',
    name: 'Current Assets',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1000',
  },
  {
    accountCode: '1110',
    name: 'Cash & Cash Equivalents',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1100',
  },
  {
    accountCode: '1111',
    name: 'Petty Cash',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1110',
  },
  {
    accountCode: '1112',
    name: 'Cash at Bank — HBL',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1110',
  },
  {
    accountCode: '1113',
    name: 'Cash at Bank — MCB',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1110',
  },
  {
    accountCode: '1120',
    name: 'Accounts Receivable',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1100',
  },
  {
    accountCode: '1121',
    name: 'Trade Debtors',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1120',
  },
  {
    accountCode: '1122',
    name: 'Allowance for Doubtful Debts',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1120',
    description: 'Contra asset — credit balance',
  },
  {
    accountCode: '1130',
    name: 'Notes Receivable',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1100',
  },
  {
    accountCode: '1140',
    name: 'Inventory',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1100',
  },
  {
    accountCode: '1141',
    name: 'Raw Materials',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1140',
  },
  {
    accountCode: '1142',
    name: 'Work in Progress',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1140',
  },
  {
    accountCode: '1143',
    name: 'Finished Goods',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1140',
  },
  {
    accountCode: '1150',
    name: 'Prepaid Expenses',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1100',
  },
  {
    accountCode: '1151',
    name: 'Prepaid Rent',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1150',
  },
  {
    accountCode: '1152',
    name: 'Prepaid Insurance',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1150',
  },
  {
    accountCode: '1160',
    name: 'Other Current Assets',
    type: AccountType.ASSET,
    subType: 'Current Asset',
    parentCode: '1100',
  },

  // Non-Current Assets
  {
    accountCode: '1200',
    name: 'Non-Current Assets',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1000',
  },
  {
    accountCode: '1210',
    name: 'Property, Plant & Equipment',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1200',
  },
  {
    accountCode: '1211',
    name: 'Land',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
  },
  {
    accountCode: '1212',
    name: 'Buildings',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
  },
  {
    accountCode: '1213',
    name: 'Accumulated Depreciation — Buildings',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
    description: 'Contra asset — credit balance',
  },
  {
    accountCode: '1214',
    name: 'Machinery & Equipment',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
  },
  {
    accountCode: '1215',
    name: 'Accumulated Depreciation — Equipment',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
    description: 'Contra asset — credit balance',
  },
  {
    accountCode: '1216',
    name: 'Vehicles',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
  },
  {
    accountCode: '1217',
    name: 'Accumulated Depreciation — Vehicles',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
    description: 'Contra asset — credit balance',
  },
  {
    accountCode: '1218',
    name: 'Furniture & Fixtures',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
  },
  {
    accountCode: '1219',
    name: 'Computers & IT Equipment',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1210',
  },
  {
    accountCode: '1220',
    name: 'Intangible Assets',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1200',
  },
  {
    accountCode: '1221',
    name: 'Goodwill',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1220',
  },
  {
    accountCode: '1222',
    name: 'Patents & Trademarks',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1220',
  },
  {
    accountCode: '1223',
    name: 'Software — Capitalized',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1220',
  },
  {
    accountCode: '1230',
    name: 'Long-Term Investments',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1200',
  },
  {
    accountCode: '1240',
    name: 'Security Deposits',
    type: AccountType.ASSET,
    subType: 'Non-Current Asset',
    parentCode: '1200',
  },

  // ── LIABILITIES (2000–2999) ──────────────────────────────────────────────
  { accountCode: '2000', name: 'Liabilities', type: AccountType.LIABILITY, subType: 'Summary' },

  // Current Liabilities
  {
    accountCode: '2100',
    name: 'Current Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2000',
  },
  {
    accountCode: '2110',
    name: 'Accounts Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },
  {
    accountCode: '2111',
    name: 'Trade Creditors',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2110',
  },
  {
    accountCode: '2120',
    name: 'Accrued Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },
  {
    accountCode: '2121',
    name: 'Accrued Salaries & Wages',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2120',
  },
  {
    accountCode: '2122',
    name: 'Accrued Rent',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2120',
  },
  {
    accountCode: '2123',
    name: 'Accrued Interest',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2120',
  },
  {
    accountCode: '2130',
    name: 'Taxes Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },
  {
    accountCode: '2131',
    name: 'Sales Tax Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2130',
  },
  {
    accountCode: '2132',
    name: 'Income Tax Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2130',
  },
  {
    accountCode: '2133',
    name: 'Withholding Tax Payable',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2130',
  },
  {
    accountCode: '2140',
    name: 'Short-Term Loans',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },
  {
    accountCode: '2150',
    name: 'Deferred Revenue',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },
  {
    accountCode: '2160',
    name: 'Customer Deposits',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },
  {
    accountCode: '2170',
    name: 'Other Current Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Current Liability',
    parentCode: '2100',
  },

  // Non-Current Liabilities
  {
    accountCode: '2200',
    name: 'Non-Current Liabilities',
    type: AccountType.LIABILITY,
    subType: 'Non-Current Liability',
    parentCode: '2000',
  },
  {
    accountCode: '2210',
    name: 'Long-Term Bank Loans',
    type: AccountType.LIABILITY,
    subType: 'Non-Current Liability',
    parentCode: '2200',
  },
  {
    accountCode: '2220',
    name: 'Deferred Tax Liability',
    type: AccountType.LIABILITY,
    subType: 'Non-Current Liability',
    parentCode: '2200',
  },
  {
    accountCode: '2230',
    name: 'Finance Lease Obligations',
    type: AccountType.LIABILITY,
    subType: 'Non-Current Liability',
    parentCode: '2200',
  },

  // ── EQUITY (3000–3999) ───────────────────────────────────────────────────
  { accountCode: '3000', name: 'Equity', type: AccountType.EQUITY, subType: 'Summary' },
  {
    accountCode: '3100',
    name: 'Share Capital',
    type: AccountType.EQUITY,
    subType: 'Paid-in Capital',
    parentCode: '3000',
  },
  {
    accountCode: '3110',
    name: 'Common Stock',
    type: AccountType.EQUITY,
    subType: 'Paid-in Capital',
    parentCode: '3100',
  },
  {
    accountCode: '3120',
    name: 'Additional Paid-in Capital',
    type: AccountType.EQUITY,
    subType: 'Paid-in Capital',
    parentCode: '3100',
  },
  {
    accountCode: '3200',
    name: 'Retained Earnings',
    type: AccountType.EQUITY,
    subType: 'Retained Earnings',
    parentCode: '3000',
  },
  {
    accountCode: '3210',
    name: 'Retained Earnings — Prior Years',
    type: AccountType.EQUITY,
    subType: 'Retained Earnings',
    parentCode: '3200',
  },
  {
    accountCode: '3220',
    name: 'Current Year Earnings',
    type: AccountType.EQUITY,
    subType: 'Retained Earnings',
    parentCode: '3200',
  },
  {
    accountCode: '3300',
    name: 'Dividends Paid',
    type: AccountType.EQUITY,
    subType: 'Dividends',
    parentCode: '3000',
    description: 'Contra equity — debit balance',
  },
  {
    accountCode: '3400',
    name: 'Owner Drawings',
    type: AccountType.EQUITY,
    subType: 'Drawings',
    parentCode: '3000',
    description: 'For sole trader / partnership',
  },

  // ── REVENUE (4000–4999) ──────────────────────────────────────────────────
  { accountCode: '4000', name: 'Revenue', type: AccountType.REVENUE, subType: 'Summary' },
  {
    accountCode: '4100',
    name: 'Operating Revenue',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4000',
  },
  {
    accountCode: '4110',
    name: 'Sales Revenue',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4100',
  },
  {
    accountCode: '4111',
    name: 'Product Sales',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4110',
  },
  {
    accountCode: '4112',
    name: 'Service Revenue',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4110',
  },
  {
    accountCode: '4113',
    name: 'SaaS Subscription Revenue',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4110',
  },
  {
    accountCode: '4120',
    name: 'Sales Returns & Allowances',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4100',
    description: 'Contra revenue — debit balance',
  },
  {
    accountCode: '4130',
    name: 'Sales Discounts',
    type: AccountType.REVENUE,
    subType: 'Operating Revenue',
    parentCode: '4100',
    description: 'Contra revenue — debit balance',
  },
  {
    accountCode: '4200',
    name: 'Other Revenue',
    type: AccountType.REVENUE,
    subType: 'Other Revenue',
    parentCode: '4000',
  },
  {
    accountCode: '4210',
    name: 'Interest Income',
    type: AccountType.REVENUE,
    subType: 'Other Revenue',
    parentCode: '4200',
  },
  {
    accountCode: '4220',
    name: 'Rental Income',
    type: AccountType.REVENUE,
    subType: 'Other Revenue',
    parentCode: '4200',
  },
  {
    accountCode: '4230',
    name: 'Gain on Asset Disposal',
    type: AccountType.REVENUE,
    subType: 'Other Revenue',
    parentCode: '4200',
  },
  {
    accountCode: '4240',
    name: 'Foreign Exchange Gain',
    type: AccountType.REVENUE,
    subType: 'Other Revenue',
    parentCode: '4200',
  },

  // ── EXPENSES (5000–9999) ─────────────────────────────────────────────────
  { accountCode: '5000', name: 'Cost of Goods Sold', type: AccountType.EXPENSE, subType: 'COGS' },
  {
    accountCode: '5100',
    name: 'Direct Material Cost',
    type: AccountType.EXPENSE,
    subType: 'COGS',
    parentCode: '5000',
  },
  {
    accountCode: '5200',
    name: 'Direct Labour Cost',
    type: AccountType.EXPENSE,
    subType: 'COGS',
    parentCode: '5000',
  },
  {
    accountCode: '5300',
    name: 'Manufacturing Overhead',
    type: AccountType.EXPENSE,
    subType: 'COGS',
    parentCode: '5000',
  },
  {
    accountCode: '5400',
    name: 'Purchase of Goods',
    type: AccountType.EXPENSE,
    subType: 'COGS',
    parentCode: '5000',
  },
  {
    accountCode: '5500',
    name: 'Freight-In',
    type: AccountType.EXPENSE,
    subType: 'COGS',
    parentCode: '5000',
  },

  {
    accountCode: '6000',
    name: 'Operating Expenses',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
  },
  {
    accountCode: '6100',
    name: 'Payroll Expenses',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6000',
  },
  {
    accountCode: '6110',
    name: 'Salaries & Wages',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6100',
  },
  {
    accountCode: '6111',
    name: 'Executive Salaries',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6110',
  },
  {
    accountCode: '6112',
    name: 'Staff Salaries',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6110',
  },
  {
    accountCode: '6113',
    name: 'Contract Labour',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6110',
  },
  {
    accountCode: '6120',
    name: 'Employee Benefits',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6100',
  },
  {
    accountCode: '6121',
    name: 'Medical Insurance',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6120',
  },
  {
    accountCode: '6122',
    name: 'Provident Fund',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6120',
  },
  {
    accountCode: '6123',
    name: 'EOBI Contributions',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6120',
  },
  {
    accountCode: '6200',
    name: 'Rent & Facilities',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6000',
  },
  {
    accountCode: '6210',
    name: 'Office Rent',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6200',
  },
  {
    accountCode: '6220',
    name: 'Utilities',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6200',
  },
  {
    accountCode: '6221',
    name: 'Electricity',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6220',
  },
  {
    accountCode: '6222',
    name: 'Gas',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6220',
  },
  {
    accountCode: '6223',
    name: 'Water',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6220',
  },
  {
    accountCode: '6230',
    name: 'Office Maintenance',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6200',
  },
  {
    accountCode: '6300',
    name: 'Technology Expenses',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6000',
  },
  {
    accountCode: '6310',
    name: 'Internet & Telecom',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6300',
  },
  {
    accountCode: '6320',
    name: 'Software Subscriptions',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6300',
  },
  {
    accountCode: '6330',
    name: 'Cloud Infrastructure',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6300',
  },
  {
    accountCode: '6340',
    name: 'IT Support & Maintenance',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6300',
  },
  {
    accountCode: '6400',
    name: 'Sales & Marketing',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6000',
  },
  {
    accountCode: '6410',
    name: 'Advertising',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6400',
  },
  {
    accountCode: '6420',
    name: 'Digital Marketing',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6400',
  },
  {
    accountCode: '6430',
    name: 'Sales Commissions',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6400',
  },
  {
    accountCode: '6440',
    name: 'Trade Shows & Events',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6400',
  },
  {
    accountCode: '6500',
    name: 'General & Administrative',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6000',
  },
  {
    accountCode: '6510',
    name: 'Office Supplies',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6520',
    name: 'Printing & Stationery',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6530',
    name: 'Travel & Transportation',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6540',
    name: 'Meals & Entertainment',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6550',
    name: 'Professional Fees',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6551',
    name: 'Audit Fees',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6550',
  },
  {
    accountCode: '6552',
    name: 'Legal Fees',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6550',
  },
  {
    accountCode: '6553',
    name: 'Consulting Fees',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6550',
  },
  {
    accountCode: '6560',
    name: 'Bank Charges & Fees',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6570',
    name: 'Postage & Courier',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6580',
    name: 'Training & Development',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6590',
    name: 'Insurance — General',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6500',
  },
  {
    accountCode: '6600',
    name: 'Depreciation & Amortisation',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6000',
  },
  {
    accountCode: '6610',
    name: 'Depreciation — Fixed Assets',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6600',
  },
  {
    accountCode: '6620',
    name: 'Amortisation — Intangibles',
    type: AccountType.EXPENSE,
    subType: 'Operating Expense',
    parentCode: '6600',
  },

  {
    accountCode: '7000',
    name: 'Financial Expenses',
    type: AccountType.EXPENSE,
    subType: 'Financial Expense',
  },
  {
    accountCode: '7100',
    name: 'Interest Expense',
    type: AccountType.EXPENSE,
    subType: 'Financial Expense',
    parentCode: '7000',
  },
  {
    accountCode: '7110',
    name: 'Interest on Bank Loans',
    type: AccountType.EXPENSE,
    subType: 'Financial Expense',
    parentCode: '7100',
  },
  {
    accountCode: '7120',
    name: 'Finance Lease Interest',
    type: AccountType.EXPENSE,
    subType: 'Financial Expense',
    parentCode: '7100',
  },
  {
    accountCode: '7200',
    name: 'Foreign Exchange Loss',
    type: AccountType.EXPENSE,
    subType: 'Financial Expense',
    parentCode: '7000',
  },

  { accountCode: '8000', name: 'Tax Expense', type: AccountType.EXPENSE, subType: 'Tax' },
  {
    accountCode: '8100',
    name: 'Income Tax Expense',
    type: AccountType.EXPENSE,
    subType: 'Tax',
    parentCode: '8000',
  },
  {
    accountCode: '8200',
    name: 'Deferred Tax Expense',
    type: AccountType.EXPENSE,
    subType: 'Tax',
    parentCode: '8000',
  },
];
